version: '3'

services:
  app:
    container_name: app
    build: ./docker
    volumes:
      - ./kakeibo:/var/www/html/kakeibo

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root