version: '3'

services:
  app:
    container_name: app
    build: ./docker
    ports:
      - 8000:443
    volumes:
      - ./kakeibo:/var/www/kakeibo
    working_dir: /var/www/kakeibo

  db:
    container_name: db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  db-test:
    container_name: db-test
    image: mysql:5.7
    ports:
      - 3000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-database
      MYSQL_USER: test-user
      MYSQL_PASSWORD: test-pass

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379