apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kakeibo
  name: kakeibo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kakeibo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kakeibo
    spec:
      containers:
      - image: gcr.io/myproject-301613/kakeibo:${CIRCLE_BUILD_NUM}
        imagePullPolicy: Always
        name: kakeibo
        ports: 
          - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi            