apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kakeibo
  name: kakeibo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32318
  selector:
    app: kakeibo
  type: NodePort