apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kakeibo
  name: kakeibo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32318
  selector:
    app: kakeibo