version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/php:7.3
        environment:
          - APP_ENV: testing
          - APP_KEY: base64:9tvXas6NOO2xwDWWvH9QuUjF5B/3asfbxx/Ejl8bQCo=
          - DB_CONNECTION: mysql
          - DB_HOST: 127.0.0.1
          - DB_PORT: 3306
          - DB_DATABASE: test-database
          - DB_USERNAME: test-user
          - DB_PASSWORD: test-password
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_DATABASE: test-database
          - MYSQL_USER: test-user
          - MYSQL_PASSWORD: test-password
    working_directory: ~/myProject
    steps:
      - checkout
      # cache composer to speed up "composer install" at the second time and after
      - restore_cache:
          # search composer.lock cache 
          # if composer.lock was changed, this key will be fail
          keys:
          - composer-v1-{{ checksum "./kakeibo/composer.lock" }}
          # search new cache
          - composer-v1-
      - run: 
          name: execute "composer install" to make vendor/
          working_directory: kakeibo
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "./kakeibo/composer.lock" }}
          paths:
            - kakeibo/vendor
      - run:
          name: install php extension to execute phpunit test
          command: |
            sudo apt-get update
            sudo apt-get install -y libfreetype6-dev libjpeg-dev libpng-dev
            sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            sudo docker-php-ext-install gd pdo_mysql
      - run:
          name: migrate database for phpunit test
          working_directory: kakeibo
          command: php artisan migrate --env=testing
      - run:
          name: execute phpunit test
          working_directory: kakeibo
          command: |
            vendor/bin/phpunit
      - persist_to_workspace:
          root: .
          paths: 
            - deploy
            - kakeibo
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: myProject
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build-docker-image
          working_directory: myProject
          command: docker build --file=deploy/Dockerfile -t kakeibo .
      - run:
          name: tag images
          working_directory: myProject
          command: |
            docker tag kakeibo gcr.io/myproject-301613/kakeibo:${CIRCLE_BUILD_NUM}
            docker tag kakeibo gcr.io/myproject-301613/kakeibo:latest
      - run:
          name: authorize Google Cloud SDK and setup default settings
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud auth configure-docker
      - run:
          name: push Docker images to GCR
          working_directory: myProject
          command: |
            docker push gcr.io/myproject-301613/kakeibo:${CIRCLE_BUILD_NUM}
            docker push gcr.io/myproject-301613/kakeibo:latest
      - run:
          name: connect to cluster
          command: |
            gcloud container clusters get-credentials cluster-kakeibo --zone us-west1-a --project ${GOOGLE_PROJECT_ID}
      - run:
          name: install gettext to use envsubst
          command: |
            apt-get update
            apt-get install -y gettext
      - run:
          name: update deployment.yaml to new tag
          working_directory: myProject
          command: |
            cat ./deploy/k8s/deployment.yaml | envsubst > ./deploy/k8s/deployment.yaml
            cat ./deploy/k8s/deployment.yaml
      - run:
          name: apply deployment.yaml
          working_directory: myProject/deploy/k8s
          command: |
            ls
            cat deployment.yaml
            kubectl apply -f deployment.yaml
      - run:
          name: apply service.yaml
          working_directory: myProject/deploy/k8s
          command: |
            kubectl apply -f service.yaml
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test