version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
        environment:
      - image: circleci/mysql:5.7-ram
        environment:
    working_directory: ~/kakeibo
    steps:
      - checkout
      - run:
          working_directory: kakeibo
          name: execute phpunit test
          command: vendor/bin/phpunit
