version: 2.1
executors:
  build-test-executor:
    docker:
      - image: circleci/php:7.3
        environment:
          - APP_ENV: testing
          - APP_KEY: base64:9tvXas6NOO2xwDWWvH9QuUjF5B/3asfbxx/Ejl8bQCo=
          - DB_CONNECTION: mysql
          - DB_HOST: 127.0.0.1
          - DB_PORT: 3306
          - DB_DATABASE: test-database
          - DB_USERNAME: test-user
          - DB_PASSWORD: test-password
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_DATABASE: test-database
          - MYSQL_USER: test-user
          - MYSQL_PASSWORD: test-password
  deploy-executor:
    docker:
      - image: google/cloud-sdk
commands:
  cache-composer:
    description: "cache composer to speed up "composer install" at the second time and after"
    steps:
      - restore_cache:
          # search the cache of composer.lock 
          # if composer.lock was changed, this key will be fail
          keys:
            # checksum "file" = hash value of "file"
            - composer-cache-{{ checksum "./kakeibo/composer.lock" }}
      - run: 
          name: execute "composer install" to make vendor/
          working_directory: kakeibo
          command: composer install -n --prefer-dist
      - save_cache:
          # chache name
          key: composer-cache-{{ checksum "./kakeibo/composer.lock" }}
          # cache file
          paths:
            - ./kakeibo/vendor
  install-extension:
    description: "install extension to execute phpunit test"
    steps:
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y libfreetype6-dev libjpeg-dev libpng-dev
            sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            sudo docker-php-ext-install gd pdo_mysql
  execute-migration:
    description: "migrate database for phpunit test"
    steps:
      - run:
          working_directory: kakeibo
          command: php artisan migrate --env=testing
  execute-phpunit:
    description: "execute phpunit test"
    steps:
      - run:
          working_directory: kakeibo
          command: vendor/bin/phpunit --log-junit tmp/test/result.xml
  store-test-result:
    description: "store test result"
    steps:
      - store_test_results:
          path: kakeibo/tmp/test
      - store_artifacts:
          path: kakeibo/tmp/test
  persist_to_workspace:
    description: "store workspace for the next job"
    steps:
      - persist_to_workspace:
          root: .
          paths: 
            - deploy
            - kakeibo
  attach_workspace:
    description: "use stored workspace at this job"
    steps:
      - attach_workspace:
          at: myProject
  - setup_remote_docker:
    description: "setup docker"
    steps:
      - setup_remote_docker:
          version: 19.03.13
  - install-envsubst:
    description: "install gettext to use envsubst"
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y gettext
  - make-env:
    description: "make env for production laravel app"
    steps:
      - run:
          working_directory: myProject
          command: cat ./deploy/env/.env.production | envsubst > ./kakeibo/.env
  - setup-permission:
    description: "setting permission to Laravel directory"
    steps:
      - run: 
          working_directory: myProject/kakeibo
          command: |
            chmod -R 777 storage/
            chmod -R 777 bootstrap/cache/
  - build-docker-image:
    description: "make docker image that includes kakeibo's source code"
    steps:
      - run:
          working_directory: myProject
          command: docker build --file=deploy/Dockerfile -t kakeibo .
  - tag-docker-image:
    description: "tag docker image"
    steps:
      - run:
          working_directory: myProject
          command: |
            docker tag kakeibo gcr.io/myproject-301613/kakeibo:${CIRCLE_BUILD_NUM}
            docker tag kakeibo gcr.io/myproject-301613/kakeibo:latest
  - authorize-google-cloud-sdk:
    description: "authorize Google Cloud SDK and setup default settings"
    steps:  
      - run:
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud auth configure-docker
  - push-docker-image-to-gcr:
    description: "push Docker images to GCR"
    steps:
      - run:
          working_directory: myProject
          command: |
            docker push gcr.io/myproject-301613/kakeibo:${CIRCLE_BUILD_NUM}
            docker push gcr.io/myproject-301613/kakeibo:latest
  - connect-to-cluster:
    description: "connect to cluster that has kakeibo's node and pods"
    steps:
      - run:
          command: gcloud container clusters get-credentials cluster-kakeibo --zone us-west1-a --project ${GOOGLE_PROJECT_ID}
  - update-deployment:
    description: "update deployment.yaml to new docker image"
    steps:
      - run:
          working_directory: myProject
          command: cat ./deploy/k8s/deployment.yaml | envsubst > ${HOME}/deployment.yaml
  - apply-deployment:
    description: "apply deployment.yaml"
    steps:
      - run:
          command: kubectl apply -f ${HOME}/deployment.yaml
  - apply-service:
    description: "apply service.yaml"
    steps:
      - run:
          working_directory: myProject/deploy/k8s
          command: kubectl apply -f service.yaml
jobs:
  build-and-test:
    executor: build-test-executor
    working_directory: ~/myProject
    steps:
      - checkout
      - cache-composer
      - install-extension
      - execute-migration
      - execute-phpunit
      - store-test-result
      - persist_to_workspace
  deploy:
    executor: deploy-executor
    steps:
      - attach_workspace
      - setup_remote_docker
      - install-envsubst
      - make-env
      - setup-permission
      - build-docker-image
      - tag-docker-image
      - authorize-google-cloud-sdk
      - push-docker-image-to-gcr
      - connect-to-cluster
      - update-deployment
      - apply-deployment
      - apply-service
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test