version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
        environment:
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test-database
          MYSQL_USER: test-user
          MYSQL_PASSWORD: test-pass
    working_directory: ~/myProject
    steps:
      - checkout
      # cache composer to speed up "composer install" at the second time and after
      - restore_cache:
          # search composer.lock cache 
          # if composer.lock was changed, this key will be fail
          keys:
          - composer-v1-{{ checksum "./kakeibo/composer.lock" }}
          # search new cache
          - composer-v1-
      - run: 
          name: execute "composer install" to make vendor/
          working_directory: kakeibo
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "./kakeibo/composer.lock" }}
          paths:
            - kakeibo/vendor
      - run:
          name: check extension
          working_directory: kakeibo
          command: |
            php -m
      - run:
          name: install mysql php extension
          command: |
            apt-get update
            docker-php-ext-install pdo_mysql
      - run:
          name: check extension second
          working_directory: kakeibo
          command: |
            php -m
      - run:
          name: migrate database for phpunit test
          working_directory: kakeibo
          command: php artisan migrate --env=testing
      - run:
          name: execute phpunit test
          working_directory: kakeibo
          command: |
            ls
            ls -a
            pwd
            cat .env.testing
            vendor/bin/phpunit
